server:
  port: 85
spring:
  application:
    name: nacos-order-comsumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8081 #配置sentinel dashboard地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始+1扫描，知道找到未被占用端口
#消费者将要去访问的微服务的名称（注册成功进nacos的微服务提供者）
server-url:
  nacos-user-service: http://nacos-payment-provider

#激活sentinel对open feign 的支持
feign:
  sentinel:
    enabled: true